from typing import List, Dict, Any, Optional

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

from src.rag.retriever import SemanticRetriever, RetrievedChunk
from src.rag.chat_memory import ChatMemoryManager
from src.model.gemini_client import GeminiClientManager
from src.core.logging_config import setup_logger

logger = setup_logger("rag_chain")


class RAGResponse:
    """Holds the final response payload including the model's response and source citations."""

    def __init__(self, answer: str, source_chunks: List[RetrievedChunk]):
        """Initializes the RAGResponse object.
        
        Args:
            answer (str): Text response generated by Gemini.
            source_chunks (List[RetrievedChunk]): The raw database chunks retrieved as supporting evidence.
        """
        self.answer = answer
        self.source_chunks = source_chunks

    def to_dict(self) -> Dict[str, Any]:
        """Converts the response and source structure to a dictionary."""
        return {
            "answer": self.answer,
            "sources": [chunk.to_dict() for chunk in self.source_chunks]
        }


class AWSCloudMentorRAGChain:
    """Orchestrates document context injection, prompt composition, LLM generation, and citation aggregation."""

    def __init__(
        self,
        retriever: SemanticRetriever,
        gemini_manager: GeminiClientManager,
        memory_manager: Optional[ChatMemoryManager] = None
    ):
        """Initializes the RAG chain orchestrator.
        
        Args:
            retriever (SemanticRetriever): Ingestion retriever instance.
            gemini_manager (GeminiClientManager): Gemini client interface.
            memory_manager (Optional[ChatMemoryManager]): Session history manager.
        """
        self.retriever = retriever
        self.gemini_manager = gemini_manager
        self.memory_manager = memory_manager
        from src.rag.comparison import AWSComparisonEngine
        self.comparison_engine = AWSComparisonEngine(retriever, gemini_manager)
        from src.rag.recommendation import AWSRecommendationEngine
        self.recommendation_engine = AWSRecommendationEngine(retriever, gemini_manager)

    def _format_context(self, chunks: List[RetrievedChunk]) -> str:
        """Formats matching vector DB results into a clean string block for the LLM context prompt."""
        formatted_blocks = []
        for idx, chunk in enumerate(chunks):
            formatted_blocks.append(
                f"--- DOCUMENT CHUNK {idx + 1} ---\n"
                f"Source File: {chunk.source}\n"
                f"Page Number: {chunk.page}\n"
                f"Content:\n{chunk.content}\n"
            )
        return "\n".join(formatted_blocks)

    def query(
        self,
        question: str,
        k: Optional[int] = None,
        session_id: Optional[str] = None
    ) -> RAGResponse:
        """Executes the standard RAG pipeline: retrieves matches, augments templates, runs LLM, and attaches citations.
        
        If a session_id and memory_manager are configured, reformulates the user question based on chat history
        to yield context-aware vector retrieval.
        
        Args:
            question (str): User's natural query.
            k (Optional[int]): Query-specific chunk threshold overrides.
            session_id (Optional[str]): Optional session tracking ID for chat history memory condensation.
            
        Returns:
            RAGResponse: Final structured response with inline answers and reference files.
            
        Raises:
            RuntimeError: If search query or LLM execution fails.
        """
        logger.info(f"Processing RAG Query: '{question}' for Session: '{session_id}'")
        try:
            # Route comparison queries to the specialized comparison engine
            if self.comparison_engine and self.comparison_engine.is_comparison_query(question):
                services = self.comparison_engine.extract_services(question)
                combined_chunks = []
                retrieved_ids = set()
                search_terms = services if services else [question]
                for term in search_terms:
                    for chunk in self.retriever.retrieve_chunks(term, k=k or 3):
                        doc_id = f"{chunk.source}_page_{chunk.page}_{hash(chunk.content)}"
                        if doc_id not in retrieved_ids:
                            retrieved_ids.add(doc_id)
                            combined_chunks.append(chunk)
                
                answer = self.comparison_engine.execute_comparison(question, services, k_per_service=k or 3)
                
                if self.memory_manager and session_id:
                    self.memory_manager.add_message(session_id, "user", question)
                    self.memory_manager.add_message(session_id, "assistant", answer)
                    
                return RAGResponse(answer=answer, source_chunks=combined_chunks)

            # Route architecture design and recommendation queries
            if self.recommendation_engine and self.recommendation_engine.is_recommendation_query(question):
                combined_chunks = self.retriever.retrieve_chunks(question, k=k or 5)
                answer = self.recommendation_engine.execute_recommendation(question, k=k or 5)
                
                if self.memory_manager and session_id:
                    self.memory_manager.add_message(session_id, "user", question)
                    self.memory_manager.add_message(session_id, "assistant", answer)
                    
                return RAGResponse(answer=answer, source_chunks=combined_chunks)

            # Rephrase query for context retrieval if chat history exists
            search_query = question
            if self.memory_manager and session_id:
                search_query = self.memory_manager.condense_question(session_id, question)

            # 1. Retrieve supporting documents using the condensed query
            retrieved_chunks = self.retriever.retrieve_chunks(search_query, k=k)
            
            if not retrieved_chunks:
                logger.warning(f"No source documentation was found related to search query '{search_query}'.")
                fallback_answer = (
                    "I'm sorry, I cannot find any relevant documentation in my knowledge base. "
                    "Please upload a PDF documentation file to help me assist you."
                )
                # Store turn to history if memory is active
                if self.memory_manager and session_id:
                    self.memory_manager.add_message(session_id, "user", question)
                    self.memory_manager.add_message(session_id, "assistant", fallback_answer)
                return RAGResponse(answer=fallback_answer, source_chunks=[])

            # 2. Build contextual string structure
            context_payload = self._format_context(retrieved_chunks)

            # 3. Formulate safety guidelines and RAG prompt templates
            system_instructions = (
                "You are CloudMentor AI, an expert Senior AWS Solutions Architect specializing in technical advisory services.\n"
                "Use the provided AWS documentation context blocks to answer the user's query.\n"
                "Follow these strict directives to guarantee correctness, safety, and clear citations:\n\n"
                "1. Grounding: Answer the question using ONLY the provided AWS documentation context. "
                "If the answer cannot be verified directly by the documentation, state "
                "\"I cannot find a direct answer in the provided documentation.\"\n"
                "2. Citations: Every statement, architecture choice, or metric you output MUST refer to its source. "
                "Cite sources inline at the end of relevant sentences using the exact format: "
                "[source: filename.pdf, page: X]. You can reference multiple page numbers if needed.\n"
                "3. No Hallucinations: Do not assume, extrapolate, or mention external features, services, or configurations "
                "not explicitly detailed in the provided context blocks.\n"
                "4. Compare Services & Advise: If asked to compare AWS services or recommend architectures, "
                "format your answer in clear, structured lists highlighting advantages, trade-offs, and service limits "
                "detailed within the context."
            )

            # Build LangChain Prompt template
            prompt_template = ChatPromptTemplate.from_messages([
                ("system", system_instructions),
                (
                    "user", 
                    "AWS DOCUMENTATION CONTEXT:\n{context}\n\n"
                    "USER QUESTION: {question}"
                )
            ])

            # Retrieve LLM and pipeline connections
            llm = self.gemini_manager.get_llm()
            
            # Construct standard LCEL generation flow
            generation_chain = prompt_template | llm | StrOutputParser()

            # 4. Invoke LLM and compile response (original question is passed here, but context was retrieved with search_query)
            logger.info("Invoking Gemini for text generation...")
            model_response = generation_chain.invoke({
                "context": context_payload,
                "question": question
            })

            # Store final turn in conversational history
            if self.memory_manager and session_id:
                self.memory_manager.add_message(session_id, "user", question)
                self.memory_manager.add_message(session_id, "assistant", model_response)

            logger.info("RAG pipeline execution finished successfully.")
            return RAGResponse(answer=model_response, source_chunks=retrieved_chunks)

        except Exception as e:
            logger.exception(f"Critical execution error during RAG query: {str(e)}")
            raise RuntimeError(f"RAG query failed: {str(e)}") from e
